baseURL = ""
title = "Marco Cornaggia"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "Marco Cornaggia"
    logo = "erblog/static/self/img/Logo3.png"
    bio = """
    portrait = "Hugo/static/img/marco-cornaggia-crop.png"
    <p> Benvenuto! </p>
    <br />
    <p>Leggi il mio blog o sbircia qualcosa di me</p>
    """
    # copyright = "Copyright © 2020, Marco Cornaggia, all rights reserved."


[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

# [[menu.main]]
#     identifier = "zone"
#     name = "Zone"
#     url = "/zone/"
#     weight = 10

[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.icon]]
    url = "mailto:marco.cornaggia.94@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/btkicio/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://www.facebook.com/marco.cornaggia.94"
    name = "facebook"
    weight = 1

[[menu.icon]]
    url = "https://www.linkedin.com/in/marco-cornaggia/"
    name = "linkedin"
    weight = 1

